### ISSUE TITLE
Possibly use the tab successor API in FF 65

### ISSUE THREAD

**Issue by indivisible** [rotemdan/ActivateLeftTabOnClose#3]
Looks like the next release of Firefox (65) will introduce a [new API](https://bugzilla.mozilla.org/show_bug.cgi?id=1500479) that should eliminate the current switching problems.

**Comment by SanderBouwhuis** [comment]
Is this true? Can the developer of this addon please check that out?

The visual jumping to the right and then to the left tab is very jarring, so if this could be fixed it would REALLY be great.

**Comment by rotemdan** [comment]
Support for the new API [has been added](https://github.com/rotemdan/ActivateLeftTabOnClose/commit/8145249dfe3a4d375041b4b69cedca694f52c6a4) in version 0.2.0, which is now published on mozilla addon site.

It sets _successorTabId_, if available, and will fall back to the previous approach as needed, i.e. force switching to the left tab at the _removed_ event (which causes the visible flicker).

Please let me know of any other issues.

**Comment by SanderBouwhuis** [comment]
It still does the same thing in Firefox v68.0.1. I have v0.2.1 of your addon, but it still jumps to the right tab before jumping to the left tab.

Steps to reproduce:
1. Press <CTRL+F4> to close a tab.
2. See the tab to the right get activated.
3. See the tab to the left get activated (shortly after 2.).

Is there a way I can see whether the 'new' method is being used? I would REALLY like this to work properly. Maybe I can test a debug / logging build of the addon for you?

**Comment by rotemdan** [comment]
Thanks for the report. In version 0.2.2 the successor update is now applied to active tabs in all windows.
(previously the code only applied it to the first window, since I wasn't sure if a highlighted tab in a non active window is considered active -- seems like that might have been the case).

Please keep me updated if you find any other issues.

**Comment by SanderBouwhuis** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSS!!!!!!!!
It works (seemingly) perfectly now.

This is sooooooooooooooooo much better. High praise, accolades, cheers, applause, and a bow for you Sir (Madam?).

Thank you, thank you, thank you!

Edit:
I worked with it for a few hours now, and it really seems to work. WHAT A FANTASTIC FIX!!!
